### ISSUE TITLE
Can ORFik be used without RNA-Seq?

### ISSUE THREAD

**Issue by yeroslaviz** [Roleren/ORFik#128]
I'm new to Riboseq, and, looking for  helpful tools, have found this R package. 

After reading the paper, I am still not sure, if it is the right one for us. We don't have RNA-Seq for our project, only Ribo-seq. 

Can ORFik be used only with Ribo-Seq data?

A second question is related to the attached enrichment profile [from this paper](https://doi.org/10.1016/j.molcel.2019.06.036).

Can this package create such a profile, or if not directly, can create a table of #reads per codon position which can be than converted to such a plot? 
I apprecaite your help, if you can point me to the respected command, or if not possible maybe you know of a tool capable of creating such enrichment plots. 

thanks

Assa

<img width="674" alt="Enrichment_profiles" src="https://user-images.githubusercontent.com/8927555/212055131-141089ff-c6d5-44be-b958-ef11abcd46bc.png">

**Comment by Roleren** [comment]
Hi, ORFik is totally agnostic about library type. You can use whatever you want, ORFik is more a swiss army knife, that has a special focus on 80S sequencing.

So yes, you can use just Ribo-seq.

These plots are very basic coverage plots, ORFik supports this, but I would strongly recommend our new graphical extension package to ORFik called RiboCrypt (install with devtools::install_github("Roleren/ORFik"), then do: devtools::install_github("m-swirski/RiboCrypt")

This is an interactive app / package on top of ORFik, you can investigate your genes and save svg / png images of your results. Example from RiboCrypt:

![Screenshot from 2023-01-12 23-06-47](https://user-images.githubusercontent.com/14344350/212191492-cd846a69-fb4c-4fee-ab07-ec4540b59f30.png)

We have also just launched a web page for deep explorative search of Ribo-seq, on [RiboCrypt.org](url)
But we have not got many species yet, since we just launched (only human, mouse and some yeast strains), there we have precomputed results for thousands of Ribo-seq libraries, and you can even use merged libraries (like 2000 libraries of human riboseq merged into 1 set, for insane coverage and detection abilities). 

Let me know what suits you, and we really need beta testers for Ribocrypt, so if you want I could help you more with getting you set up, if you need the local app (If you have personal Riboseq datasets we do not host on RiboCrypt.org, another organism etc)

**Comment by yeroslaviz** [comment]
Thanks for the elaborate explanation and mentioning the `RiboCrypt` package. I will definitely look into it.  I would also love to be one of the beta-testers for your package, if you need me to test any of the commands/functions. 

For now though, as I am quite new to riboseq, I'm trying to understand the data in general and how it is structured. 
(as you mentioned in the ribocrypt vignette, I'm still trying to understand the offset and the p-shifting). 

I really also appreciate your willingness to help me setup the analysis. 
As i have read a few papers, people are analysing riboseq data by the workflow `cutadapt` -> `bowtie`. In your paper (and vignette) you mention `fastp` for the trimming and the `star` aligner for mapping. 

Are you mapping against the complete transcriptome with `star`? 
what parameters are being used when mapping with STAR to assure good mapping (and quality) results with unique, short reads?

For now we are working with yeast and human samples, but we definitely plan also to run some mouse and even _C. elegans_ samples in the future. 

I hope we can help each other.

thanks again

**Comment by Roleren** [comment]
Cutadapt and bowtie is the old way, many people are now trying to push the field towards a more modern standard, where we believe fastp and Star is the future (for now at least). For input parameters, I would suggest looking at the documentation for the ORFik function STAR.align.folder function, it discusses a lot of the important things to use. The default values there should be sufficient, you could maybe get 1% more coverage with tweaked, but usually not worth it. So only tweak if you see your data has low total genome coverage.

**Comment by yeroslaviz** [comment]
Yes, I can report very low mapping results. both with bowtie-cutadapt as well as with STAR. 

Is the STAR log final out being saved somewhere?

**Comment by Roleren** [comment]
That means one of 3 things usually. 

- Run fastqc to validate that the adapter you trim is indeed correct (it is shown in overrepresented sequences)
- You have barcodes/UMIs that are still there and are too large, which makes the minimum proportion of read to be mapped fail.
-  You aligned to the wrong organism (mouse vs rat is a common one)

**Comment by Roleren** [comment]
The STAR log file is saved in the aligned folder as ./LOGS/00_STAR_LOG_table.csv.

**Comment by yeroslaviz** [comment]
Yes, I have found them. I was surprised tehy were missing, but the problem was that STAR didn't finish the mapping, so they were not written. Now they are there.
