### ISSUE TITLE
Feature request for translation start site seq data

### ISSUE THREAD

**Issue by m-jahn** [Roleren/ORFik#139]
I'm currently using ORFik to compute ORF-centered features from RNA-Seq and Ribo-Seq data. I want to use the features in a  machine-learning model to predict novel ORFs.
I was wondering if it is possible to integrate also Retapamulin-Ribo-Seq data, that means RPF data that is specific for start codons (see e.g. [this publication](https://pubmed.ncbi.nlm.nih.gov/30904393/)). Right now I'm using such data to compute features from ORFs in the same way I use conventional Ribo-Seq data, but it feels like a very generic solution. Since the data is specific for translation start sites, the interesting region is only around the start codon, and some of the computed features that expect coverage for the entire ORF might not make sense.

My questions are:

- is there an optimal way to include this type of data?
- would you recommend to exclude or include certain features for this type of data?

Thanks for your work on this package!
Michael

**Comment by Roleren** [comment]
Yes, so I thought about this actually, and there are some easy solutions (which have their drawbacks of course).

So let's say you want to do ORFik::computeFeatures or something related that usually takes whole ORFs. What you can do now, is
to define a short version of the ORF and input it instead.

My suggestion is something like:

`shorter_ORFs <- startRegion(ORFs, upstream = 0, downstream = 15)`

And use that object. 
Also, some of the features are less interesting, and some become less statistically significant if you shorten the region (like ORFscore periodicity).

Some features like coverage over ORF vs upstream region now become nonsensical, because upstream of your shorter ORF is still usually in the original ORF. So maybe just ignore them.

You can make your own versions of those easily if needed.

You could get coverage upstream of the whole ORF and compare to coverage of start region etc.

As far as I know, of there are no designated packages for large-scale QTI-seq analysis, so ORFik is what I would use.

If you have any more features you had in mind let me know and I can suggest some solutions.

**Comment by m-jahn** [comment]
Hi Hakon, thanks for your quick reply.

Using a truncated pseudo ORF around the start codon is exactly what I had in mind too.
Regarding the features you propose, I will look into how computed features behave for these short pseudo-ORFs. 

Maybe one or two additional features for translation initiation seq data could be scores that rate
- A) the peak intensity/AUC around the start codon
- B) the peak "sharpness" i.e. dispersion around the start codon (I noticed that canonical ORFs often have a really sharp peak)

I think more about this and maybe get back with suggestions.

**Comment by Roleren** [comment]
So I have been playing with known ways to score these short ORFs, and the current classifiers I think are highly lacking. 

There are 3 scores here that I think are good:
1. Count the number of peaks in close start region divided by a larger window start region.  So lets say the 6 bases around TIS / 21 bases around TIS. If this number is high, it means you have a sharp peak. Another more statistical rigorous way could be to use ORFik:::findPeaksPerGene(), then you check if any of the hits are from TISs. This uses zscore normalized peak detection.


2. A very good score I believe which is not used yet is to do a frame specific upstream check.
So lets say ORF starts on position 100. You check the start region and compared to upstream per frame. 
So if you see reads upstream that are frame biased in the same frame as your ORF, then you know this ORF is most likely not real, and there is an ORF upstream in the same frame.
If the upstream coverage is out of frame there is an out of frame ORF etc.

To get the coverage upstream you could do something like:
```
upstream_of_ORF <- startRegion(ORFs, upstream = 20, downstream = -1) # Upstream from each ORF
coveragePerTiling(upstream_of_ORF, as.data.table = TRUE, withFrames = TRUE)
```
Now you have a lot of cool information to make a frame-specific filter for upstream peaks etc. 

3. Another cool feature I can come up with from the top of my head, is to find TIS peaks. Then check if there has been a stop codon after that, if not, all in-frame start codons further downstream can be supposed to be "fake", they are really just peaks from that bigger ORF. 

Related to peak intensity, a good intro is here, to get you to think about how you would do it:
https://www.baeldung.com/cs/signal-peak-detection

**Comment by Roleren** [comment]
Hey, need any more help needed here or was it resolved ? 
If not I will close this issue in a week

**Comment by m-jahn** [comment]
Yes, sorry for not getting back. In the end I roughly followed the conclusion we had in our discussion and did _not_ use the `computeFeatures` function which is only suitable for RPF data. I came up with a new function that calculates a handful of features based on a narrow window around the supposed translation start site. These features include raw RPKM count, TE, peak shape, and peak accuracy (alignment with start codon).
From my part you can close the issue, but maybe include a function that computes features for RPF-start site data. It could be included in the computeFeatures function with a toggle that defines the type of RPF data.
