### ISSUE TITLE
Questions about the manual and results

### ISSUE THREAD

**Issue by Arek86** [Roleren/ORFik#180]
Hi Roleren,

Thank you for such a great and powerful tool like ORFik. It's excellent and well-written or explained.
Although, I have a few questions about the manual and my results:

1. In the ORFik manual on page 108, there is information that states: "Analysis is done between each possible combination of levels in the target contrast If target contrast is condition column, with factor levels: WT, mut1 and mut2 with 3 replicates each. You get comparison of WT vs mut1, WT vs mut2 and mut1 vs mut2." This description suggests that WT is compared to the mutants. Is it just worded this way, and in reality, are the mutants compared to WT?
2. The commands "DTEG.analysis" and "DEG.analysis" both calculate log fold change for RNA-Seq data (column "rna" in DTEG and "LFC" in DEG). I noticed that the log fold changes from these commands differ slightly. Why does this happen? Shouldn't they be the same?
3. When I calculate fold change using "fpkmRNA" or "fpkmRFP" received via the command "computeFeatures," it's different from the fold change calculated by the commands "DTEG.analysis" and "DEG.analysis." Am I correct in understanding that this is due to the way normalization and FC calculation are performed in these commands, which comes from DESeq2?
4. I didn't find any transcripts present in the RNA-Seq but absent in the RIBO-Seq. Is this observation specific to my experiment, or are transcripts with no RIBO-Seq signal somehow removed from the analysis?
5. How exactly is translation efficiency (TE) calculated?
a. Mutant(log(FPKM RIBO-Seq / FPKM RNA-Seq)) / WT(log(FPKM RIBO-Seq / FPKM RNA-Seq))
or
b. RIBO-Seq logFC (mutant/WT) divided by RNA-Seq logFC (mutant/WT)

I hope I've presented these questions clearly.
Thank you for your answers.
Cheers,
Arek

**Comment by Roleren** [comment]
1. If I get your question you wonder what the numerator and the denominator is.
DEseq can only compare 2 levels of the contrast like column called condition.
What is compared is given in the Comparison column of output. What comes first is given in pairs input argument: So numerator is pairs[[1]][1] and denominator is pairs[[1]][2]

2. No, they should not be the same, as DESeq has more information to normalize for in DTEG. But they should be quite similar.
3. FPKM ratio is different from same reason as above, fpkm ratio does not raw count normalization schemes like DESeq does.
4. P value must be defined, to create a category. If all counts are 0 for a gene, it will give NA. And calculation is ignored. This is simply a feature of DESeq. If you really want to include 0 count genes in analysis, then run FPKM ratios with a pseudo count. I have never needed that myself at least.
5. I here interpret you to ask about what DTEG.analysis defines as a TE difference:
It does neither of those, as it uses DESeq contrast design defined as:
```
te.design <- as.formula(paste0("~ libtype + ", be,
                                 paste(design, collapse = " + "),
                                 "+ libtype:", target.contrast))
```
Example would be : ~ librarytype + condition + librarytype/condition.
So that is most similar to what you called a (the condition is the primary thing tested, not the library types, they are only factors in a design)
This is then run through a significant test to give final result.

**Comment by Arek86** [comment]
Thank you for quick response :)
Everything is clear now.

Best!
